version: '3.4'
services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-discovery-db}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: